# Site settings
title: Jason Scott blog
email:
description: "Ramblings in SAP technology and other stuff..."
baseurl: ""
url: "http://js1972.github.io"
twitter_username: js1972
github_username: js1972

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
